export const EVENTS = {
  EDITOR_EXPORT_TO_JSON: "EDITOR_EXPORT_TO_JSON",
  REQUEST_EDITOR_EXPORT_TO_JSON: "REQUEST_EDITOR_EXPORT_TO_JSON",
  REQUEST_SET_DATA: "REQUEST_SET_DATA",
};

export const PAYLOAD_TYPE = {};
