export const stickers = [
  {
    id: "ZEtHYcsJVEP-JdXWxvC9Q",
    src: "https://ik.imagekit.io/lh/shapes/zavCJryGqqGYXQz8ZovYQQT4.svg",
    type: "StaticVector",
    name: "001-birthday.svg",
    colorMap: {},
    metadata: {
      category: "STICKER",
      collectionId: "ytLSxmdeK00FssNKGKD0c",
      collectionName: "Birthday",
      style: "Solid",
    },
  },
  {
    id: "zd0Ujds5o1BvFskoxmzkY",
    src: "https://ik.imagekit.io/lh/shapes/KavVmmWu0SCj4n00Dxr7_0X4.svg",
    type: "StaticVector",
    name: "002-birthday.svg",
    colorMap: {},
    metadata: {
      category: "STICKER",
      collectionId: "ytLSxmdeK00FssNKGKD0c",
      collectionName: "Birthday",
      style: "Solid",
    },
  },
  {
    id: "QiwfiMAQntzZEq6uEqcBQ",
    src: "https://ik.imagekit.io/lh/shapes/AkeRaXZz7k_tAkmqeRQ34x54.svg",
    type: "StaticVector",
    name: "003-gift.svg",
    colorMap: {},
    metadata: {
      category: "STICKER",
      collectionId: "ytLSxmdeK00FssNKGKD0c",
      collectionName: "Birthday",
      style: "Solid",
    },
  },
  {
    id: "GryLUYAWLwVkpcKDPywJL",
    src: "https://ik.imagekit.io/lh/shapes/TrIUNq3P3hRt6XmPGdoNuekU.svg",
    type: "StaticVector",
    name: "004-birthday cake.svg",
    colorMap: {},
    metadata: {
      category: "STICKER",
      collectionId: "ytLSxmdeK00FssNKGKD0c",
      collectionName: "Birthday",
      style: "Solid",
    },
  },
  {
    id: "s0W4_tUnkOsM7nKPVxWEy",
    src: "https://ik.imagekit.io/lh/shapes/93wUODpNAcqNwJVTucssGGNr.svg",
    type: "StaticVector",
    name: "005-cupcake.svg",
    colorMap: {},
    metadata: {
      category: "STICKER",
      collectionId: "ytLSxmdeK00FssNKGKD0c",
      collectionName: "Birthday",
      style: "Solid",
    },
  },
  {
    id: "MmxCmMBpU1V4ow4VVP9rh",
    src: "https://ik.imagekit.io/lh/shapes/WZdF1_8ItRW_nrAy9_i_7Wam.svg",
    type: "StaticVector",
    name: "006-birthday cake.svg",
    colorMap: {},
    metadata: {
      category: "STICKER",
      collectionId: "ytLSxmdeK00FssNKGKD0c",
      collectionName: "Birthday",
      style: "Solid",
    },
  },
  {
    id: "LOctE1rQzH6qcAKEzGTTo",
    src: "https://ik.imagekit.io/lh/shapes/7LpQsOiEzV80gTCAub4L2nax.svg",
    type: "StaticVector",
    name: "007-cupcake.svg",
    colorMap: {},
    metadata: {
      category: "STICKER",
      collectionId: "ytLSxmdeK00FssNKGKD0c",
      collectionName: "Birthday",
      style: "Solid",
    },
  },
  {
    id: "hK7JYCbu-V-ZglnD4MFr6",
    src: "https://ik.imagekit.io/lh/shapes/2p67wjwgMVOizKpmAgaAVtUi.svg",
    type: "StaticVector",
    name: "008-birthday.svg",
    colorMap: {},
    metadata: {
      category: "STICKER",
      collectionId: "ytLSxmdeK00FssNKGKD0c",
      collectionName: "Birthday",
      style: "Solid",
    },
  },
  {
    id: "ZlPL6BnzYqr37vQpgIlBC",
    src: "https://ik.imagekit.io/lh/shapes/5vAd2iFT_H6eTqHgtXF4lg74.svg",
    type: "StaticVector",
    name: "009-birthday.svg",
    colorMap: {},
    metadata: {
      category: "STICKER",
      collectionId: "ytLSxmdeK00FssNKGKD0c",
      collectionName: "Birthday",
      style: "Solid",
    },
  },
  {
    id: "YLKiiAHG55oarS4rdeNG5",
    src: "https://ik.imagekit.io/lh/shapes/H8ENriCIAp_H8svRXuNpJT2O.svg",
    type: "StaticVector",
    name: "010-birthday cake.svg",
    colorMap: {},
    metadata: {
      category: "STICKER",
      collectionId: "ytLSxmdeK00FssNKGKD0c",
      collectionName: "Birthday",
      style: "Solid",
    },
  },
  {
    id: "cPNRc42TAEHZ5fm2cP7Dw",
    src: "https://ik.imagekit.io/lh/shapes/dJOcw3nE1zoeW6pUpQwTwZiM.svg",
    type: "StaticVector",
    name: "011-gift.svg",
    colorMap: {},
    metadata: {
      category: "STICKER",
      collectionId: "ytLSxmdeK00FssNKGKD0c",
      collectionName: "Birthday",
      style: "Solid",
    },
  },
  {
    id: "eCkQon_biPHgD7482A_Ra",
    src: "https://ik.imagekit.io/lh/shapes/PFqdwwD2ns4_EAk722rokkiJ.svg",
    type: "StaticVector",
    name: "012-ice cream.svg",
    colorMap: {},
    metadata: {
      category: "STICKER",
      collectionId: "ytLSxmdeK00FssNKGKD0c",
      collectionName: "Birthday",
      style: "Solid",
    },
  },
  {
    id: "9VTqWRN_rjX3FO7e-UGAu",
    src: "https://ik.imagekit.io/lh/shapes/vWgKaCsSMBu7yNPUEdi15xLY.svg",
    type: "StaticVector",
    name: "013-cupcake.svg",
    colorMap: {},
    metadata: {
      category: "STICKER",
      collectionId: "ytLSxmdeK00FssNKGKD0c",
      collectionName: "Birthday",
      style: "Solid",
    },
  },
  {
    id: "iQGcBcg5y8ORp8S3lSZ0N",
    src: "https://ik.imagekit.io/lh/shapes/hc88p4hT9kM8mjbVI6BYWpt3.svg",
    type: "StaticVector",
    name: "014-gift.svg",
    colorMap: {},
    metadata: {
      category: "STICKER",
      collectionId: "ytLSxmdeK00FssNKGKD0c",
      collectionName: "Birthday",
      style: "Solid",
    },
  },
  {
    id: "5Ms8MvR7Sr6QvNdKUgDd8",
    src: "https://ik.imagekit.io/lh/shapes/VyQ3JBbJROAcOAaIjP6561Li.svg",
    type: "StaticVector",
    name: "015-birthday.svg",
    colorMap: {},
    metadata: {
      category: "STICKER",
      collectionId: "ytLSxmdeK00FssNKGKD0c",
      collectionName: "Birthday",
      style: "Solid",
    },
  },
  {
    id: "wKEu_vj434iZpbwCythNV",
    src: "https://ik.imagekit.io/lh/shapes/hErfmxLRRubqdQlSabh0CGOt.svg",
    type: "StaticVector",
    name: "016-balloons.svg",
    colorMap: {},
    metadata: {
      category: "STICKER",
      collectionId: "ytLSxmdeK00FssNKGKD0c",
      collectionName: "Birthday",
      style: "Solid",
    },
  },
  {
    id: "oFA6IShYfAEz6XLzueJ5W",
    src: "https://ik.imagekit.io/lh/shapes/gctg2Oqk7cdwD8meDYUTOGWt.svg",
    type: "StaticVector",
    name: "017-birthday cake.svg",
    colorMap: {},
    metadata: {
      category: "STICKER",
      collectionId: "ytLSxmdeK00FssNKGKD0c",
      collectionName: "Birthday",
      style: "Solid",
    },
  },
  {
    id: "13sPdpRPtIlScl54uFMW0",
    src: "https://ik.imagekit.io/lh/shapes/yx2Ayz8k8Urn9GpSotpXaA7g.svg",
    type: "StaticVector",
    name: "018-birthday.svg",
    colorMap: {},
    metadata: {
      category: "STICKER",
      collectionId: "ytLSxmdeK00FssNKGKD0c",
      collectionName: "Birthday",
      style: "Solid",
    },
  },
  {
    id: "QPpHbYjoJfnBchYJWNi1Y",
    src: "https://ik.imagekit.io/lh/shapes/XQ_AO5TMxzjvDhvF9S3PoliB.svg",
    type: "StaticVector",
    name: "019-birthday.svg",
    colorMap: {},
    metadata: {
      category: "STICKER",
      collectionId: "ytLSxmdeK00FssNKGKD0c",
      collectionName: "Birthday",
      style: "Solid",
    },
  },
  {
    id: "sUz1uf8BZ-MCD17kCo7V6",
    src: "https://ik.imagekit.io/lh/shapes/630WYS74VI6sakvB_2yjVh5t.svg",
    type: "StaticVector",
    name: "020-birthday.svg",
    colorMap: {},
    metadata: {
      category: "STICKER",
      collectionId: "ytLSxmdeK00FssNKGKD0c",
      collectionName: "Birthday",
      style: "Solid",
    },
  },
];

export const images = [
  {
    id: 3493777,
    preview:
      "https://images.pexels.com/photos/3493777/pexels-photo-3493777.jpeg?auto=compress&cs=tinysrgb&h=130",
    src: "https://images.pexels.com/photos/3493777/pexels-photo-3493777.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    type: "StaticImage",
  },
  {
    id: 1683492,
    preview:
      "https://images.pexels.com/photos/1683492/pexels-photo-1683492.jpeg?auto=compress&cs=tinysrgb&h=130",
    src: "https://images.pexels.com/photos/1683492/pexels-photo-1683492.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    type: "StaticImage",
  },
  {
    id: 789555,
    preview:
      "https://images.pexels.com/photos/789555/pexels-photo-789555.jpeg?auto=compress&cs=tinysrgb&h=130",
    src: "https://images.pexels.com/photos/789555/pexels-photo-789555.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    type: "StaticImage",
  },
  {
    id: 2894944,
    preview:
      "https://images.pexels.com/photos/2894944/pexels-photo-2894944.jpeg?auto=compress&cs=tinysrgb&h=130",
    src: "https://images.pexels.com/photos/2894944/pexels-photo-2894944.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    type: "StaticImage",
  },
  {
    id: 2437286,
    preview:
      "https://images.pexels.com/photos/2437286/pexels-photo-2437286.jpeg?auto=compress&cs=tinysrgb&h=130",
    src: "https://images.pexels.com/photos/2437286/pexels-photo-2437286.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    type: "StaticImage",
  },
  {
    id: 670741,
    preview:
      "https://images.pexels.com/photos/670741/pexels-photo-670741.jpeg?auto=compress&cs=tinysrgb&h=130",
    src: "https://images.pexels.com/photos/670741/pexels-photo-670741.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    type: "StaticImage",
  },
  {
    id: 105808,
    preview:
      "https://images.pexels.com/photos/105808/pexels-photo-105808.jpeg?auto=compress&cs=tinysrgb&h=130",
    src: "https://images.pexels.com/photos/105808/pexels-photo-105808.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    type: "StaticImage",
  },
  {
    id: 694587,
    preview:
      "https://images.pexels.com/photos/694587/pexels-photo-694587.jpeg?auto=compress&cs=tinysrgb&h=130",
    src: "https://images.pexels.com/photos/694587/pexels-photo-694587.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    type: "StaticImage",
  },
  {
    id: 4275360,
    preview:
      "https://images.pexels.com/photos/4275360/pexels-photo-4275360.jpeg?auto=compress&cs=tinysrgb&h=130",
    src: "https://images.pexels.com/photos/4275360/pexels-photo-4275360.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    type: "StaticImage",
  },
  {
    id: 7494171,
    preview:
      "https://images.pexels.com/photos/7494171/pexels-photo-7494171.jpeg?auto=compress&cs=tinysrgb&h=130",
    src: "https://images.pexels.com/photos/7494171/pexels-photo-7494171.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    type: "StaticImage",
  },
  {
    id: 5846615,
    preview:
      "https://images.pexels.com/photos/5846615/pexels-photo-5846615.jpeg?auto=compress&cs=tinysrgb&h=130",
    src: "https://images.pexels.com/photos/5846615/pexels-photo-5846615.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    type: "StaticImage",
  },
  {
    id: 5840879,
    preview:
      "https://images.pexels.com/photos/5840879/pexels-photo-5840879.jpeg?auto=compress&cs=tinysrgb&h=130",
    src: "https://images.pexels.com/photos/5840879/pexels-photo-5840879.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    type: "StaticImage",
  },
  {
    id: 5815904,
    preview:
      "https://images.pexels.com/photos/5815904/pexels-photo-5815904.jpeg?auto=compress&cs=tinysrgb&h=130",
    src: "https://images.pexels.com/photos/5815904/pexels-photo-5815904.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    type: "StaticImage",
  },
  {
    id: 12736377,
    preview:
      "https://images.pexels.com/photos/12736377/pexels-photo-12736377.jpeg?auto=compress&cs=tinysrgb&h=130",
    src: "https://images.pexels.com/photos/12736377/pexels-photo-12736377.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    type: "StaticImage",
  },
  {
    id: 9246817,
    preview:
      "https://images.pexels.com/photos/9246817/pexels-photo-9246817.jpeg?auto=compress&cs=tinysrgb&h=130",
    src: "https://images.pexels.com/photos/9246817/pexels-photo-9246817.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    type: "StaticImage",
  },
  {
    id: 5694948,
    preview:
      "https://images.pexels.com/photos/5694948/pexels-photo-5694948.jpeg?auto=compress&cs=tinysrgb&h=130",
    src: "https://images.pexels.com/photos/5694948/pexels-photo-5694948.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    type: "StaticImage",
  },
  {
    id: 12229836,
    preview:
      "https://images.pexels.com/photos/12229836/pexels-photo-12229836.jpeg?auto=compress&cs=tinysrgb&h=130",
    src: "https://images.pexels.com/photos/12229836/pexels-photo-12229836.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    type: "StaticImage",
  },
  {
    id: 12569708,
    preview:
      "https://images.pexels.com/photos/12569708/pexels-photo-12569708.jpeg?auto=compress&cs=tinysrgb&h=130",
    src: "https://images.pexels.com/photos/12569708/pexels-photo-12569708.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    type: "StaticImage",
  },
  {
    id: 12569707,
    preview:
      "https://images.pexels.com/photos/12569707/pexels-photo-12569707.jpeg?auto=compress&cs=tinysrgb&h=130",
    src: "https://images.pexels.com/photos/12569707/pexels-photo-12569707.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    type: "StaticImage",
  },
  {
    id: 12573639,
    preview:
      "https://images.pexels.com/photos/12573639/pexels-photo-12573639.jpeg?auto=compress&cs=tinysrgb&h=130",
    src: "https://images.pexels.com/photos/12573639/pexels-photo-12573639.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    type: "StaticImage",
  },
];

export const templates = [
  {
    id: "dsg_DzxpADIMbZ",
    name: "Untitled project",
    type: "GRAPHIC",
    published: true,
    createdAt: "2022-11-09T22:35:01.408Z",
    updatedAt: "2022-11-11T16:16:41.066Z",
    frame: {
      width: 1920,
      height: 1080,
      dpi: 300,
      unit: "PIXELS",
      name: "Facebook Event Cover",
    },
    previews: [
      {
        src: "https://ik.imagekit.io/ddqq3alnl/trzNikqdEr.png",
      },
    ],
    scenes: [
      {
        name: "Initial scene",
        layers: [
          {
            id: "background",
            name: "Initial Frame",
            angle: 0,
            stroke: null,
            strokeWidth: 0,
            left: 0,
            top: 0,
            width: 1920,
            height: 1080,
            opacity: 1,
            originX: "left",
            originY: "top",
            scaleX: 1,
            scaleY: 1,
            type: "Background",
            flipX: false,
            flipY: false,
            skewX: 0,
            skewY: 0,
            visible: true,
            shadow: {
              color: "#fcfcfc",
              blur: 4,
              offsetX: 0,
              offsetY: 0,
              affectStroke: false,
              nonScaling: false,
            },
            fill: "#47CA19",
            metadata: {},
          },
          {
            id: "eJUEr3mOsAcPIvJ0ddnF0",
            name: "StaticText",
            angle: 0,
            stroke: null,
            strokeWidth: 0,
            left: 433.15,
            top: 362.6,
            width: 240,
            height: 70.06,
            opacity: 1,
            originX: "left",
            originY: "top",
            scaleX: 1,
            scaleY: 1,
            type: "StaticText",
            flipX: false,
            flipY: false,
            skewX: 0,
            skewY: 0,
            visible: true,
            shadow: null,
            charSpacing: 0,
            fill: "#333333",
            fontFamily: "Comfortaa-Bold",
            fontSize: 62,
            lineHeight: 1.16,
            text: "YEP",
            textAlign: "center",
            fontURL:
              "https://fonts.gstatic.com/s/comfortaa/v34/1Pt_g8LJRfWJmhDAuUsSQamb1W0lwk4S4Y_LPrQVIT9c2c8.ttf",
            params: [],
          },
          {
            id: "FPU8VbQudLR15Hg0Ig9AI",
            name: "StaticText",
            angle: 0,
            stroke: null,
            strokeWidth: 0,
            left: 433.15,
            top: 484.88,
            width: 240,
            height: 70.06,
            opacity: 1,
            originX: "left",
            originY: "top",
            scaleX: 1,
            scaleY: 1,
            type: "StaticText",
            flipX: false,
            flipY: false,
            skewX: 0,
            skewY: 0,
            visible: true,
            shadow: null,
            charSpacing: 0,
            fill: "#03a9f4",
            fontFamily: "IndieFlower",
            fontSize: 62,
            lineHeight: 1.16,
            text: "Add title",
            textAlign: "center",
            fontURL:
              "https://fonts.gstatic.com/s/indieflower/v12/m8JVjfNVeKWVnh3QMuKkFcZlbkGG1dKEDw.ttf",
            metadata: {
              category: "single",
              types: ["StaticText"],
            },
            params: [],
          },
        ],
      },
    ],
  },
  {
    id: "dsg_FmJplrFjxM",
    name: "Untitled project",
    type: "GRAPHIC",
    published: true,
    createdAt: "2022-11-09T23:59:13.181Z",
    updatedAt: "2022-11-11T15:59:46.980Z",
    frame: {
      width: 1920,
      height: 1080,
      dpi: 300,
      unit: "PIXELS",
      name: "Facebook Event Cover",
    },
    previews: [
      {
        src: "https://ik.imagekit.io/ddqq3alnl/bjRxJbsomk.png",
      },
    ],
    scenes: [
      {
        name: "Initial scene",
        layers: [
          {
            id: "background",
            name: "Initial Frame",
            angle: 0,
            stroke: null,
            strokeWidth: 0,
            left: 0,
            top: 0,
            width: 1920,
            height: 1080,
            opacity: 1,
            originX: "left",
            originY: "top",
            scaleX: 1,
            scaleY: 1,
            type: "Background",
            flipX: false,
            flipY: false,
            skewX: 0,
            skewY: 0,
            visible: true,
            shadow: {
              color: "#fcfcfc",
              blur: 4,
              offsetX: 0,
              offsetY: 0,
              affectStroke: false,
              nonScaling: false,
            },
            fill: "#0986FA",
            metadata: {},
          },
          {
            id: "MitFkQbay1Zr6w7F_NNLi",
            name: "StaticText",
            angle: 0,
            stroke: null,
            strokeWidth: 0,
            left: 840,
            top: 504.97,
            width: 240,
            height: 70.06,
            opacity: 1,
            originX: "left",
            originY: "top",
            scaleX: 1,
            scaleY: 1,
            type: "StaticText",
            flipX: false,
            flipY: false,
            skewX: 0,
            skewY: 0,
            visible: true,
            shadow: null,
            charSpacing: 0,
            fill: "#333333",
            fontFamily: "Roboto-Regular",
            fontSize: 62,
            lineHeight: 1.16,
            text: "Add title",
            textAlign: "center",
            fontURL:
              "https://fonts.gstatic.com/s/roboto/v29/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf",
            params: [],
          },
        ],
      },
    ],
  },
  {
    id: "dsg_nTPxLcYMZp",
    name: "Untitled project",
    type: "GRAPHIC",
    published: true,
    createdAt: "2022-11-08T23:19:31.511Z",
    updatedAt: "2022-11-09T20:07:14.201Z",
    frame: {
      width: 1920,
      height: 1080,
      dpi: 300,
      unit: "PIXELS",
      name: "Facebook Event Cover",
    },
    previews: [
      {
        src: "https://ik.imagekit.io/ddqq3alnl/EkeachHJSO.png",
      },
    ],
    scenes: [
      {
        name: "Initial scene",
        layers: [
          {
            id: "background",
            name: "Initial Frame",
            angle: 0,
            stroke: null,
            strokeWidth: 0,
            left: 0,
            top: 0,
            width: 1920,
            height: 1080,
            opacity: 1,
            originX: "left",
            originY: "top",
            scaleX: 1,
            scaleY: 1,
            type: "Background",
            flipX: false,
            flipY: false,
            skewX: 0,
            skewY: 0,
            visible: true,
            shadow: {
              color: "#fcfcfc",
              blur: 4,
              offsetX: 0,
              offsetY: 0,
              affectStroke: false,
              nonScaling: false,
            },
            fill: "#18061d",
            metadata: {},
          },
          {
            id: "XUiVtDX5c5v7ROCzj7uq_",
            name: "StaticText",
            angle: 0,
            stroke: null,
            strokeWidth: 0,
            left: 338.17,
            top: 333.69,
            width: 843.08,
            height: 412.63,
            opacity: 1,
            originX: "left",
            originY: "top",
            scaleX: 1,
            scaleY: 1,
            type: "StaticText",
            flipX: false,
            flipY: false,
            skewX: 0,
            skewY: 0,
            visible: true,
            shadow: null,
            charSpacing: 100,
            fill: "#eb00ff",
            fontFamily: "NothingYouCouldDo",
            fontSize: 169.05496681801847,
            lineHeight: 1.16,
            text: "Hello Tinywow",
            textAlign: "left",
            fontURL:
              "https://fonts.gstatic.com/s/nothingyoucoulddo/v10/oY1B8fbBpaP5OX3DtrRYf_Q2BPB1SnfZb0OJl1ol2Ymo.ttf",
            params: [],
          },
        ],
      },
    ],
  },
];
